mkt_roi/mkt_roi/app/urls.py
from django.urls import path
from . import views 
from django.contrib.auth import views as auth_views
# agregamos el logout
app_name='app'
urlpatterns = [
 #login basico 
  path('', views.user_login, name='login')  ,
  # vistas que replican los exceles y hacen inserts a la DB
  path('medios_en_tienda_excel/', views.MediosEnTiendaExcel.as_view(), name='medios_en_tienda_excel'), 
  path('medios_off_line_excel/', views.MKTOffLineExcel.as_view(), name='medios_off_line_excel'), 
  path('e_marketing_excel/', views.EMarketing.as_view(), name='e_marketing_excel'), 
  path('relaciones_publicas_excel/', views.RelacionesPublicas.as_view(), name='relaciones_publicas_excel'), 
  path('mercadotecnia_excel/', views.Mercadotecnia.as_view(), name='mercadotecnia_excel'), 
  path('medicion_digital_excel/', views.MedicionDigital.as_view(), name='medicion_digital_excel'), 
  path('mkt_digital_excel/', views.MKtDigital.as_view(), name='mkt_digital_excel'), 



  path('menu/', views.Menu, name='menu'),
  path('gracias/', views.Gracias, name='gracias' ) ,
  # este es el interesante
  path('update/<pk>/', views.Update.as_view(), name='update'), 
  path('update/', views.Update.as_view(), name='update'), 

  # nada de interesante 
  path('lista_campanias/', views.ListaCampanias, name='lista_campanias'), 
  
  # agregamos el logout
  path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

mkt_roi/mkt_roi/mkt_roi/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', include('app.urls')),     
     
    path('admin/', admin.site.urls),   
]

mkt_roi/mkt_roi/app/templates/app/dashboard.html
{% extends "base.html" %}
{% block title %}Dashboard{% endblock %}
{% block content %}
<h1>Dashboard</h1>
<p>Welcome to your dashboard.</p>
{% endblock %}

mkt_roi/mkt_roi/app/templates/app/e_marketing_index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% csrf_token %}
<table style="width:100%">
    <tr>
        <img style="float: left;" alt=""src="{% static 'images/coppel.png' %}" >    </tr>
   </tr>
</table> 
<h1>E-Marketing</h1>

<h2>Bienvenido </h2>
<h3> Que se rife Edmundo aqui  Lorem Ipsum</h3>
<p>"Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..."</p>

<table style="width:100%">
    {% if request.user.is_authenticated %}
    <h4>Menu</h4>
    <tr> <td class='texto_izq'>Hola {{ request.user.first_name }} </td> 
       </tr>

    <tr> <td class='texto_izq'> <a href="{% url "app:e_marketing_excel" %}"  >Carga de esfuerzos </a>  </td> 
        <td class='texto_der;'> <a href="{% url "app:lista_campanias" %}"  >Consulta o corrección de esfuerzos anteriores </a> </td>  
    {% endif %}
    
</table>
<p>


</p>
<p>

</p>
<table style="width:100%">
    <tr>  <td class='texto_der;'> <a href="{% url "app:logout" %}"  > <b>Logout </b></a>  </td> 
        <td class='texto_'> Powered by <img style="float: right;" alt=""src="{% static 'images/cenic.png' %}">   </td>
    </tr>
</table>
{% endblock %}

mkt_roi/mkt_roi/app/templates/app/lista_capanias.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h3>Su Lista de campañas</h3>
{%if n > 0 %}
<form method="post" name="{{campania_id}}"   action="{% url 'app:update' %}">
    {% csrf_token %}

{%for x in campanias %}
<ul>
    <li> <a href={% url 'app:update' pk=x.id  %} > {{x.nombre}} </a> </li> <!-- https://stackoverflow.com/questions/19428572/django-templatesyntaxerror-could-not-parse-the-remainder-->
    
</ul>
{% endfor%}

{% else %}
Usted no tiene campañas registradas 

<thead>
    <table>
        <tr> <th> <a href="{% url "app:menu" %}" > Ir al Menu </a>  </th> 
            <th> <a href="{% url "app:logout" %}"  >Logout</a>     </th>
        </tr>
    </table>
    </thead>

{% endif %}

{% endblock %}

mkt_roi/mkt_roi/app/templates/app/medicion_digital_excel.html
{% extends 'base.html' %}
{% block content %}
<form method="post" id="exceldata"  action="{% url 'app:medicion_digital_excel' %}">

    {% csrf_token %}
    <label for="name">Nombre de campaña:</label>
    <input type="text" id="campaña" name="campaña"> 
<table border="1" style="width:100%" id="excel">
<thead>

    <tr>
      <th scope="col"  >  </th>
      <th scope="col"  >  </th>
      <th scope="col" colspan="3" rowspan="2" >Objetivo macro </th>
      <th scope="col" colspan="3" > Retail </th>
      <th scope="col" colspan="8"> Unidad de negocio que atiende </th>
      </tr>
</thead>
<tr rowspan="2">
    <th scope="col"  >  </th>
    <th scope="col"  >  </th>
    <th scope="col" colspan="3"  > </th>
    <th scope="col" colspan="3" ></th>
    <th scope="col" colspan="5"> Sevicios Financieros  </th>
    <th scope="col" colspan="2"> Nuevos formatos  </th>
    <th scope="col" colspan="1"> Atención a Grupo Coppel	 </th>
</tr>
<tbody>      
      <script> //esta marranada fue para hacer un array que permita mandar en el post toda la data con ids faciles de identificar y meter en la DB
     var  text = '';
     var long_text =  document.getElementById("excel").innerHTML ;

      var columnas = [];
      var Objetivos_macro = ['Performance', 'Merca directa', 'Personalización'];
      var Retail =  ['Ropa', 'Muebles', 'Zapatos']; 
      var Segmentos = [ 'Crédito Coppel', 'Préstamo personal', 'Coppel Pay', 'Seguros(Club de Protección)',
                        'Fondo de retiro','Coppel Motos', 'Fashion Market', 'Market Place'];
      
      var WEB = ['Buscador', 'Personalización']; 
      columnas = Objetivos_macro.concat(Retail).concat(Segmentos);
      
      var subcanales = Array(WEB.length ); 
    
      var inutil =[WEB];
      var contador = 0;
      for(j in inutil){
      for( i in inutil[j]) {
       subcanales[contador]= {'canal': mapeo(inutil[j][i]), 'columnas': columnas, 'subcanal': inutil[j][i]};
       contador+=1;
      }}

function mapeo(canal){
    
    if( WEB.includes(canal) ) return 'Web';
   
    else return 'no jala';
}
    long_text+= '<tr >  <td> Canal </td> <td> Subcanal </td> '; 
    text ='';
    for (x in columnas){
        text+= '<td> ' + columnas[x] + ' </td>';
    }
    text +='</tr>';
    var bandera_span =true;
    var n_canales_init = 0;//numero de elementos del primer canal 
    var n_canales = 0;
    for( row in subcanales ){
        text+= '<tr> '
            n_canales =subcanales.filter(x=> x.canal==subcanales[row].canal ).length;
            if( n_canales != n_canales_init) bandera_span =true;
            if( bandera_span==true){
                text+='<td rowspan="'+ subcanales.filter(x=> x.canal==subcanales[row].canal ).length +'"> '+subcanales[row].canal+' </td> <td>'+ subcanales[row].subcanal +'</td> ';
                for( c in subcanales[row].columnas){
                    text+= '<td> <input type="checkbox" name="'+ subcanales[row].canal +'.'+ subcanales[row].subcanal +'.'
                        +subcanales[row].columnas[c]+ '" value=True > </td>';
                }
                text+='</tr>';
                bandera_span =false;
            } else {
                text+=' <td>'+ subcanales[row].subcanal +'</td> ';
                for( c in subcanales[row].columnas){
                    text+= '<td> <input type="checkbox" name="'+ subcanales[row].canal +'.'+ subcanales[row].subcanal +'.'+subcanales[row].columnas[c]+ '" value=True > </td>';
                }
                text+='</tr>';
            }
            n_canales_init = n_canales;
        }
        
     long_text += text; //+'<input type="submit" value="Carga de datos">';
     document.getElementById("excel").innerHTML =  long_text; 
      </script>
</tbody>
       </table>  
        <input type="submit" value="Guardar datos">
        </form>
 

{% endblock %}

mkt_roi/mkt_roi/app/templates/app/medicion_digital_index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% csrf_token %}
<table style="width:100%">
    <tr>
        <img style="float: left;" alt=""src="{% static 'images/coppel.png' %}" >    </tr>
   </tr>
</table> 
<h1>Medición digital</h1>

<h2>Bienvenido </h2>
<h3> Que se rife Edmundo aqui  Lorem Ipsum</h3>
<p>"Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..."</p>

<table style="width:100%">
    {% if request.user.is_authenticated %}
    <h4>Menu</h4>
    <tr> <td class='texto_izq'>Hola {{ request.user.first_name }} </td> 
       </tr>

    <tr> <td class='texto_izq'> <a href="{% url "app:medicion_digital_excel" %}"  >Carga de esfuerzos </a>  </td> 
        <td class='texto_der;'> <a href="{% url "app:lista_campanias" %}"  >Consulta o corrección de esfuerzos anteriores </a> </td>  
    {% endif %}
    
</table>
<p>


</p>
<p>

</p>
<table style="width:100%">
    <tr>  <td class='texto_der;'> <a href="{% url "app:logout" %}"  > <b>Logout </b></a>  </td> 
        <td class='texto_'> Powered by <img style="float: right;" alt=""src="{% static 'images/cenic.png' %}">   </td>
    </tr>
</table>
{% endblock %}

mkt_roi/mkt_roi/app/templates/app/medios_en_tienda_index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<img style="float: left;" alt=""src="{% static 'images/coppel.png' %}" >
<br>
<br> 
<br>medios en tienda 
<br> 
<h1>Lorem Ipsum</h1>
<p>"Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..."</p>
<!--<a href="{% url 'app:login' %}">Log In</a>
    ALGUN DIA AQUI IRA EL LOG-OUT-->
    {% if request.user.is_authenticated %}
    Hello {{ request.user.first_name }},
    <a href="{% url "app:logout" %}"  >Logout</a>
    {% endif %}
<p style="float: right;">Powered by  <img style="float: right;" alt=""src="{% static 'images/cenic.png' %}"> </p>
{% endblock %}

mkt_roi/mkt_roi/app/templates/app/medios_off_line_excel.html
{% extends 'base.html' %}
{% block content %}
<form method="post" id="exceldata"  action="{% url 'app:medios_off_line_excel' %}">

    {% csrf_token %}
    <label for="name" class="texto_der">Nombre de campaña :     &nbsp; </label> 
    <div style="overflow: hidden; padding-right: .5em;">
        <input type="text" id="campaña" name="campaña" style="width: 20%;">  
     </div>    
     <p> &nbsp; 
        &nbsp; 
     </p>
<table style="width:100%; border: 1px solid #5b87fa" id="excel">
<thead class="excel_header">

    <tr>
      <th scope="col"  >  </th>
      <th scope="col"  >  </th>
      <th scope="col" colspan="3" rowspan="2" >Objetivo macro </th>
      <th scope="col" colspan="3" > Retail </th>
      <th scope="col" colspan="8"> Unidad de negocio que atiende </th>
      </tr>
</thead>
<tr rowspan="2" class="excel_header">
    <th scope="col"  >  </th>
    <th scope="col"  >  </th>
    <th scope="col" colspan="3"  > </th>
    <th scope="col" colspan="3" ></th>
    <th scope="col" colspan="4"> Sevicios Financieros  </th>
    <th scope="col" colspan="2"> Nuevos formatos  </th>
    <th scope="col" colspan="2"> Atención a Grupo Coppel	 </th>
</tr>
<tbody>      
      <script> //esta marranada fue para hacer un array que permita mandar en el post toda la data con ids faciles de identificar y meter en la DB
     var  text = '';
     var long_text =  document.getElementById("excel").innerHTML ;

      var columnas = [];
      var Objetivos_macro = ['Branding', 'Coppel comunidad', 'Performance'];//, 'Merca Directa', 'Personalización'];
      var Retail =  ['Ropa', 'Muebles', 'Zapatos']; 
      var Segmentos = [ 'Crédito Coppel', 'Préstamo personal', 'Coppel Pay', //Fondo de retiro',
                         'Seguros (Club de Protección)',
                       'Coppel Motos', 'Fashion Market',//'Comunicación interna',
                        'Atracción de talento', 'Plan de lealtad'];
      columnas = Objetivos_macro.concat(Retail).concat(Segmentos);
      
      var Impresos=['Periódico Coppel', 'Revista Coppel', 'Tickets en tienda', 'Prensa', 'Revista Nacional'] ;// VARIAN DE AREA A AREA
      var TV = ['TV de Paga', 'TV Abierta'];// agregamos lo fijo que varia de area a area 
      var Radio = ['Radio'];
      var Exteriores = ['Metro', 'Metrobus', 'Parabuses', 'Carteleras', 'Camiones Urbanos', 'Estaciones Solares'];
      var Otros = ['Deportes'];
      var subcanales = Array(Impresos.length +TV.length + Radio.length +Exteriores.length+ Otros.length); //ESTE ES EL BUENO
      var inutil =[Impresos, TV, Radio, Exteriores, Otros];
      var contador = 0;
      for(j in inutil){
      for( i in inutil[j]) {
       subcanales[contador]= {'canal': mapeo(inutil[j][i], Impresos, TV, Radio, Exteriores, Otros), 'columnas': columnas, 'subcanal': inutil[j][i]};
       contador+=1;
      }}

function mapeo(canal){
    
    if( Impresos.includes(canal) ) return 'Impresos';
    if( TV.includes(canal) ) return  'TV';
    if( Radio.includes(canal) ) return  'Radio';
    if( Exteriores.includes(canal) ) return  'Exteriores';
    if( Otros.includes(canal) ) return  'Otros';
    else return 'no jala';
}
    long_text+= '<tr class="excel_header">  <td> Canal </td> <td> Subcanal </td> '; 
    text ='';
    for (x in columnas){
        text+= '<td> ' + columnas[x] + ' </td>';
    }
    text +='</tr>';
    var bandera_span =true;
    var n_canales_init = 0;//numero de elementos del primer canal 
    var n_canales = 0;
    for( row in subcanales ){
        text+= '<tr> '
            n_canales =subcanales.filter(x=> x.canal==subcanales[row].canal ).length;
            if( n_canales != n_canales_init) bandera_span =true;
            if( bandera_span==true){
                text+='<td class="excel_row" rowspan="'+ subcanales.filter(x=> x.canal==subcanales[row].canal ).length +'"> '+subcanales[row].canal+' </td> <td class="excel_row">'+ subcanales[row].subcanal +'</td> ';
                for( c in subcanales[row].columnas){
                    text+= '<td class="center-check-box" > <input type="checkbox" name="'+ subcanales[row].canal +'.'+ subcanales[row].subcanal +'.'
                        +subcanales[row].columnas[c]+ '" value=True > </td>';
                }
                text+='</tr>';
                bandera_span =false;
            } else {
                text+=' <td class="excel_row">'+ subcanales[row].subcanal +'</td> ';
                for( c in subcanales[row].columnas){
                    text+= '<td class="excel_cuadro" > <input type="checkbox" name="'+ subcanales[row].canal +'.'+ subcanales[row].subcanal +'.'+subcanales[row].columnas[c]+ '" value=True > </td>';
                }
                text+='</tr>';
            }
            n_canales_init = n_canales;
        }
        
     long_text += text; //+'<input type="submit" value="Carga de datos">';
     document.getElementById("excel").innerHTML =  long_text; 
      </script>
</tbody>
       </table>  
        <input type="submit" value="Guardar datos">
        </form>
 

{% endblock %}

mkt_roi/mkt_roi/app/templates/app/medios_off_line_form.html
{% extends 'base.html' %}
{% block content %}


<form method="post" id="carga"   action="{% url 'app:login' %}">
    {% csrf_token %}
<table border="1" style="width:100%" >
<thead>
    <tr>
      <th > Campaña </th>
      <th > Objetivo macro </th>
      <th > Segmento </th>
      <th > Canal  </th>
      <th > Sub canal </th>
      <th > Inicio  </th>
      <th > Fin </th>
      <th > Gasto </th>
    </tr>
</thead>
<tbody> 
    <!-- check esta referencia super cool https://stackoverflow.com/questions/8018973/how-to-iterate-through-dictionary-in-a-dictionary-in-django-template-->
{%for dict in form %}

<tr> <td> <input type="text" id="campaña" name="campaña"> </td> 
     <td> {{dict.objetivo_macro}}   </td> 
      <td>   {{ dict.segmento}} </td>
        <td> {{dict.canal}}</td>
         <td> {{dict.subcanal}}  </td>  
    <td> <input type="date" id="inicio" name="inicio"> </td> 
    <td> <input type="date" id="fin" name="fin"> </td> 
    <td> <input type="number" step="any" id="gasto"></input> </td></tr>
  
    
{% endfor %}

</tbody>  
</table>  
<!--<input type="submit" value="Preparar de datos">'-->
<input type="submit" value="Preparar de datos">'
</form>
{% endblock %}

mkt_roi/mkt_roi/app/templates/app/mercadotecnia_excel.html
{% extends 'base.html' %}
{% block content %}
<form method="post" id="exceldata"  action="{% url 'app:mercadotecnia_excel' %}">

    {% csrf_token %}
    <label for="name">Nombre de campaña:</label>
    <input type="text" id="campaña" name="campaña"> 
<table border="1" style="width:100%" id="excel">
<thead>

    <tr>
      <th scope="col"  >  </th>
      <th scope="col"  >  </th>
      <th scope="col" colspan="5" rowspan="2" >Objetivo macro </th>
      <th scope="col" colspan="3" > Retail </th>
      <th scope="col" colspan="6"> Unidad de negocio que atiende </th>
      </tr>
</thead>
<tr rowspan="2">
    <th scope="col"  >  </th>
    <th scope="col"  >  </th>
    <th scope="col" colspan="5"  > </th>
    <th scope="col" colspan="3" ></th>
    <th scope="col" colspan="4"> Sevicios Financieros  </th>
    <th scope="col" colspan="2"> Nuevos formatos  </th>
 </tr>
<tbody>      
      <script> //esta marranada fue para hacer un array que permita mandar en el post toda la data con ids faciles de identificar y meter en la DB
     var  text = '';
     var long_text =  document.getElementById("excel").innerHTML ;

      var columnas = [];
      var Objetivos_macro = ['Branding', 'Coppel comunidad', 'Performance', 'Merca Directa', 'Personalización'];
      var Retail =  ['Ropa', 'Muebles', 'Zapatos']; 
      var Segmentos = [ 'Crédito Coppel', 'Préstamo personal', 'Seguros(Club de Protección)',
                        'Fondo de retiro','Coppel Motos','Fashion Market'];
      columnas = Objetivos_macro.concat(Retail).concat(Segmentos);
      
      var Impresos = ['Cartas','Periódico Coppel', 'Revista Coppel', 'Tickets en tienda', 'Prensa', 'Revista Nacional', 'Estado de cuenta'];
      var TV = ['TV de paga', 'TV abierta'];
      var Telefono = ['Llamadas', 'SMS'];
      var Radio = ['Radio'];
      var Comunicacion_en_tienda = ['Pantallas en micros', 'Aparador', 'Audio Ambiental', 'Banderas', 'Material POP', 'Poster Coppel', 'Poster Coppel CANADA', 'Comunicacion visual en tienda'];
      var Otros = ['Comunicado de prensa/contenido', 'Spoke person', 'Entrevista uno a uno', ' Concursos/Sorteos', 'Trivia', 'Eventos con medios','Producto integrado', 'Fachadas en tienda', 'Patrocinios externos', 'Publicidad exterior'];
      var subcanales = Array(Impresos.length +TV.length + Telefono.length + Radio.length+Comunicacion_en_tienda.length+
      Otros.length  ); //ESTE ES EL BUENO
      var inutil =[Impresos, TV, Radio, Telefono, Comunicacion_en_tienda, Otros];
      var contador = 0;
      for(j in inutil){
      for( i in inutil[j]) {
       subcanales[contador]= {'canal': mapeo(inutil[j][i]), 'columnas': columnas, 'subcanal': inutil[j][i]};
       contador+=1;
      }}

function mapeo(canal){
    
    if( Impresos.includes(canal) ) return 'Impresos';
    if( TV.includes(canal) ) return  'TV';
    if( Radio.includes(canal) ) return  'Radio';
    if( Telefono.includes(canal) ) return  'Telefono';
    if( Otros.includes(canal) ) return  'Otros';
    if( Comunicacion_en_tienda.includes(canal)) return 'Comunicación en tienda' ;
    else return 'no jala';
}
    long_text+= '<tr >  <td> Canal </td> <td> Subcanal </td> '; 
    text ='';
    for (x in columnas){
        text+= '<td> ' + columnas[x] + ' </td>';
    }
    text +='</tr>';
    var bandera_span =true;
    var n_canales_init = 0;//numero de elementos del primer canal 
    var n_canales = 0;
    for( row in subcanales ){
        text+= '<tr> '
            n_canales =subcanales.filter(x=> x.canal==subcanales[row].canal ).length;
            if( n_canales != n_canales_init) bandera_span =true;
            if( bandera_span==true){
                text+='<td rowspan="'+ subcanales.filter(x=> x.canal==subcanales[row].canal ).length +'"> '+subcanales[row].canal+' </td> <td>'+ subcanales[row].subcanal +'</td> ';
                for( c in subcanales[row].columnas){
                    text+= '<td> <input type="checkbox" name="'+ subcanales[row].canal +'.'+ subcanales[row].subcanal +'.'
                        +subcanales[row].columnas[c]+ '" value=True > </td>';
                }
                text+='</tr>';
                bandera_span =false;
            } else {
                text+=' <td>'+ subcanales[row].subcanal +'</td> ';
                for( c in subcanales[row].columnas){
                    text+= '<td> <input type="checkbox" name="'+ subcanales[row].canal +'.'+ subcanales[row].subcanal +'.'+subcanales[row].columnas[c]+ '" value=True > </td>';
                }
                text+='</tr>';
            }
            n_canales_init = n_canales;
        }
        
     long_text += text; //+'<input type="submit" value="Carga de datos">';
     document.getElementById("excel").innerHTML =  long_text; 
      </script>
</tbody>
       </table>  
        <input type="submit" value="Guardar datos">
        </form>
 

{% endblock %}

mkt_roi/mkt_roi/app/templates/app/mercadotecnia_index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% csrf_token %}
<table style="width:100%">
    <tr>
        <img style="float: left;" alt=""src="{% static 'images/coppel.png' %}" >    </tr>
   </tr>
</table> 
<h1>Mercadotecnia</h1>

<h2>Bienvenido </h2>
<h3> Que se rife Edmundo aqui  Lorem Ipsum</h3>
<p>"Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..."</p>

<table style="width:100%">
    {% if request.user.is_authenticated %}
    <h4>Menu</h4>
    <tr> <td class='texto_izq'>Hola {{ request.user.first_name }} </td> 
       </tr>

    <tr> <td class='texto_izq'> <a href="{% url "app:mercadotecnia_excel" %}"  >Carga de esfuerzos </a>  </td> 
        <td class='texto_der;'> <a href="{% url "app:lista_campanias" %}"  >Consulta o corrección de esfuerzos anteriores </a> </td>  
    {% endif %}
    
</table>
<p>


</p>
<p>

</p>
<table style="width:100%">
    <tr>  <td class='texto_der;'> <a href="{% url "app:logout" %}"  > <b>Logout </b></a>  </td> 
        <td class='texto_'> Powered by <img style="float: right;" alt=""src="{% static 'images/cenic.png' %}">   </td>
    </tr>
</table>
{% endblock %}

mkt_roi/mkt_roi/app/templates/app/mkt_digital_index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% csrf_token %}
<table style="width:100%">
    <tr>
        <img style="float: left;" alt=""src="{% static 'images/coppel.png' %}" >    </tr>
   </tr>
</table> 
<h1>MKt Digítal</h1>

<h2>Bienvenido </h2>
<h3> Que se rife Edmundo aqui  Lorem Ipsum</h3>
<p>"Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..."</p>

<table style="width:100%">
    {% if request.user.is_authenticated %}
    <h4>Menu</h4>
    <tr> <td class='texto_izq'>Hola {{ request.user.first_name }} </td> 
       </tr>

    <tr> <td class='texto_izq'> <a href="{% url "app:mkt_digital_excel" %}"  >Carga de esfuerzos </a>  </td> 
        <td class='texto_der;'> <a href="{% url "app:lista_campanias" %}"  >Consulta o corrección de esfuerzos anteriores </a> </td>  
    {% endif %}
    
</table>
<p>


</p>
<p>

</p>
<table style="width:100%">
    <tr>  <td class='texto_der;'> <a href="{% url "app:logout" %}"  > <b>Logout </b></a>  </td> 
        <td class='texto_'> Powered by <img style="float: right;" alt=""src="{% static 'images/cenic.png' %}">   </td>
    </tr>
</table>
{% endblock %}

mkt_roi/mkt_roi/app/templates/app/update.html
{% extends 'base.html' %}
{% block content %}

<form method="post" name="{{campania_id}}"   action="{% url 'app:update' %}">
    {% csrf_token %}
<table style="width:100%; border: 1px solid #5b87fa"  style="width:100%" >
<thead class="excel_header">
    <tr>
      <th > Campaña </th>
      <th > Objetivo macro </th>
      <th > Segmento </th>
      <th > Canal  </th>
      <th > Sub canal </th>
      <th > Inicio  </th>
      <th > Fin </th>
      <th > Gasto </th>
    </tr>
</thead>
<tbody> 
    <!-- check esta referencia super cool https://stackoverflow.com/questions/8018973/how-to-iterate-through-dictionary-in-a-dictionary-in-django-template-->
{%for registro in esfuerzos %}

<tr> <input type="hidden" name="id" value="{{registro.id}}" >
       <td class="excel_row"> {{campania}} </td> 
       <td class="excel_row"> {{registro.objetivo_macro}}   </td> 
       <td  class="excel_row">   {{ registro.segmento}} </td>
       <td  class="excel_row"> {{registro.canal}}</td>
       <td  class="excel_row"> {{registro.subcanal }}   </td>  
    <td  class="excel_cuadro" > <input type="date"  name="inicio"  value={{registro.inicio|date:"Y-m-d"}}>  
         </td>

    <td class="excel_cuadro">  <input type="date"  name="fin"   value="{{registro.fin|date:"Y-m-d"}}"> 
    <td class="excel_cuadro"> <input type="number" step="any"  name="gasto" value={{registro.gasto}}> </td>
  </tr>
{% endfor %}

</tbody>  
</table>  
<!--<input type="submit" value="Preparar de datos">'-->
<input type="submit" value="Guardar datos">'
</form>
{% endblock %}